name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
    - run: npm install
    - run: npm run build
    - run: npm run test
    - run: npm run-script lint
    - run: npm run-script tslint
